"""Sound-effect catalogue: ``render_sfx(id, **params) -> (2, n) float64 @ 48 kHz``.

Every effect is a registered ``SfxSpec``: a generator plus metadata (purpose,
suggested sync, anchor point, parameter ranges, reference level). All effects
share the same parameter vocabulary where it makes sense:

* ``pitch``  semitones relative to the effect's native tuning
* ``bright`` 0..1 timbre brightness (filter cut-off / FM index / air layer)
* ``dur``    seconds (overall length or decay length, see the catalogue)
* ``seed``   int; the same (id, params, seed) always renders the same samples

Reference level ("统一响度归一"): after rendering, every effect is normalised
to its class reference, either a true-peak target (``tp``, dBTP, short
transients) or a max-momentary-loudness target (``mmax``, LUFS over a 400 ms
window, sustained sounds). The references are designed for a voice track at
-16 LUFS integrated; the master stage moves everything together, so gain_db = 0
in a cue means "sits at its designed level against speech". See
sfx/CATALOG.md (generated by ``python cli.py catalog``).
"""
import warnings
import zlib
from dataclasses import dataclass, field

import numpy as np

from . import instruments as ins
from . import meter
from .dsp import (SR, TWOPI, smp, hz, midi, semis, noise, rc_ramp, lp, hp, bpf, dual_mono,
                  stereo, db2lin, dc_block, fade_edges, get_ir, convolve_st, decimate, att_curve as _att)


# =============================================================================
# registry
# =============================================================================
@dataclass
class SfxSpec:
    id: str
    fn: object                      # fn(rng, seed, **params) -> (n,) or (2, n)
    purpose: str                    # 用途
    sync: str                       # 建议对位
    anchor: str                     # 'start' | 'peak' | 'end' | 'mark'
    ref: tuple                      # ('tp', dBTP) or ('mmax', LUFS)
    params: dict                    # name -> (default, lo, hi, note)
    family: str = 'sfx'             # 'sfx' | 'ident'
    humanize_db: float = 0.0        # random level spread (+-dB) applied after normalisation
    lead_frames: float = 0.0        # align='motion': sound starts this many frames before the visual action
    mark_s: object = None           # callable(params) -> seconds, for anchor == 'mark'
    notes: str = ''
    aliases: tuple = field(default_factory=tuple)


REGISTRY = {}
ALIASES = {}


def register(spec):
    REGISTRY[spec.id] = spec
    for a in spec.aliases:
        ALIASES[a] = spec.id
    return spec


def list_sfx(family=None):
    return [k for k, s in REGISTRY.items() if family is None or s.family == family]


def get_spec(sfx_id):
    sid = ALIASES.get(sfx_id, sfx_id)
    if sid not in REGISTRY:
        raise KeyError('unknown sfx id %r (known: %s)' % (sfx_id, ', '.join(sorted(REGISTRY))))
    return REGISTRY[sid]


def _resolve(spec, params):
    out = {}
    for k, v in params.items():
        if k not in spec.params:
            raise TypeError('%s: unknown parameter %r (allowed: %s)' % (spec.id, k, ', '.join(spec.params)))
    for k, (default, lo, hi, _) in spec.params.items():
        v = params.get(k, default)
        if lo is not None and isinstance(v, (int, float, np.floating)) and not isinstance(v, bool):
            if v < lo or v > hi:
                warnings.warn('%s: %s=%r outside [%r, %r], clipped' % (spec.id, k, v, lo, hi), stacklevel=3)
                v = min(max(v, lo), hi)
        out[k] = v
    return out


def _finish(y, spec, seed, normalize=True, gain_db=0.0):
    y = np.asarray(y, dtype=np.float64)
    if y.ndim == 1:
        y = dual_mono(y)
    # DC-safe: 20 ms of silence lets the 12 Hz high-pass settle, then trim + fade
    n = y.shape[1]
    y = dc_block(np.hstack([y, np.zeros((2, smp(0.02)))]))[:, :n]
    y = fade_edges(y, 0.0003, 0.003)
    if normalize:
        kind, target = spec.ref
        lvl = meter.true_peak_db(y) if kind == 'tp' else meter.max_momentary(y)
        if np.isfinite(lvl):
            y = y * db2lin(target - lvl)
    if spec.humanize_db > 0:
        r = np.random.default_rng(zlib.crc32(('%s|%d|lvl' % (spec.id, seed)).encode()))
        y = y * db2lin(r.uniform(-spec.humanize_db, spec.humanize_db))
    if gain_db:
        y = y * db2lin(gain_db)
    return y


def render_sfx(sfx_id, seed=0, normalize=True, gain_db=0.0, **params):
    """Render one sound effect -> float64 (2, n) at 48 kHz, starting and ending
    at digital zero, normalised to the class reference level (unless
    normalize=False). Unknown parameters raise TypeError; out-of-range values
    are clipped with a warning."""
    spec = get_spec(sfx_id)
    p = _resolve(spec, params)
    rng = np.random.default_rng(zlib.crc32(('%s|%d' % (spec.id, int(seed))).encode()))
    y = spec.fn(rng, int(seed), **p)
    return _finish(y, spec, int(seed), normalize, gain_db)


def anchor_offset(sfx_id, y, mode=None, **params):
    """sample offset of the effect's sync point inside a rendered buffer
    (mode overrides the class anchor: 'start' | 'end' | 'peak' | 'mark')."""
    spec = get_spec(sfx_id)
    mode = mode or spec.anchor
    if mode == 'start':
        return 0
    if mode == 'end':
        return y.shape[1]
    if mode == 'mark' and spec.mark_s is not None:
        p = _resolve(spec, params)
        return smp(spec.mark_s(p))
    # 'peak': maximum of the 10 ms RMS envelope
    e = np.sum(y * y, axis=0)
    w = smp(0.010)
    c = np.concatenate([[0.0], np.cumsum(e)])
    r = c[w:] - c[:-w]
    return int(np.argmax(r) + w // 2)


# =============================================================================
# helpers
# =============================================================================
def _b(bright, span=1.6):
    """brightness 0..1 -> frequency multiplier 2^((b-0.5)*span)."""
    return 2.0 ** ((bright - 0.5) * span)


def _space(y, amount, ir='plate', tail=1.0):
    """add a synthetic plate/room/hall reverb (returns stereo, length + tail)."""
    y = dual_mono(y) if y.ndim == 1 else y
    if amount <= 0:
        return y
    n = y.shape[1] + smp(tail)
    dry = np.hstack([y, np.zeros((2, n - y.shape[1]))])
    wet = convolve_st(hp(dry, 200, 2), get_ir(ir), n)
    out = dry + amount * wet * 0.35
    nf = min(n // 2, smp(0.25))
    out[:, -nf:] *= rc_ramp(nf)[::-1]
    return out


def _note(p, default):
    base = p.get('note') or default
    return midi(base) + p.get('pitch', 0.0)


P_PITCH = (0.0, -12.0, 12.0, 'semitones')
P_BRIGHT = (0.5, 0.0, 1.0, '0 dark .. 1 bright')


# =============================================================================
# generators
# =============================================================================
_WHOOSH = {
    'fast': dict(dur=0.30, f_lo=700.0, f_hi=3600.0, peak=0.42, q=1.3, travel=0.7, dmin=0.15, dmax=0.5),
    'mid': dict(dur=0.60, f_lo=380.0, f_hi=2600.0, peak=0.55, q=1.2, travel=0.6, dmin=0.35, dmax=1.0),
    'slow': dict(dur=1.20, f_lo=240.0, f_hi=1900.0, peak=0.60, q=1.0, travel=0.5, dmin=0.8, dmax=3.0),
}


def _whoosh_fn(speed):
    base = _WHOOSH[speed]

    def fn(rng, seed, pitch=0.0, bright=0.5, dur=base['dur'], travel=base['travel'], peak=base['peak']):
        r = semis(pitch)
        f_lo = base['f_lo'] * r
        f_hi = min(base['f_hi'] * r * _b(bright), 12000.0)
        pk = float(peak)

        def fc_curve(u):              # rises with the swell, falls ~40 % back after the peak (pass-by)
            up = np.clip(u / pk, 0, 1) ** 1.2
            down = np.clip((u - pk) / (1 - pk), 0, 1) ** 0.8
            return up - 0.4 * down

        return ins.whoosh(dur, f_lo, f_hi, 'swell', q=base['q'], pan0=-travel, pan1=travel, seed=seed * 7 + 11,
                          lowmix=0.35, fade_out=0.006, peak=pk, fc_curve=fc_curve, air=0.25 * bright)
    return fn


for _sp, _zh, _sync in (
        ('fast', '快切、卡片弹出、镜头急推、字幕飞入', '峰值在 42% 处：比位移起点提前 3–4 帧（30 fps）放置，峰值落在速度最快的那一帧附近'),
        ('mid', '常规转场、元素横移、画面推拉', '峰值在 55% 处：比位移起点提前 4–6 帧放置；或用 align=peak 直接对准最快帧'),
        ('slow', '大段落转场、场景切换、慢推镜', '峰值在 60% 处：比转场起点提前 8–12 帧；用 align=peak 对准切点')):
    _b0 = _WHOOSH[_sp]
    register(SfxSpec(
        id='whoosh_' + _sp, fn=_whoosh_fn(_sp), purpose=_zh, sync=_sync, anchor='peak', ref=('mmax', -23.0),
        params={'pitch': P_PITCH, 'bright': P_BRIGHT,
                'dur': (_b0['dur'], _b0['dmin'], _b0['dmax'], 'seconds'),
                'travel': (_b0['travel'], -1.0, 1.0, 'pan sweep: +L->R, -R->L, 0 static'),
                'peak': (_b0['peak'], 0.2, 0.8, 'loudness peak position (fraction of dur)')},
        notes='带通噪声扫频 + 低八度层 + 高频空气层，中心频率随包络先升后回落（掠过感），声像按 travel 移动。',
        lead_frames={'fast': 3.5, 'mid': 5.0, 'slow': 10.0}[_sp],
        aliases=('whoosh',) if _sp == 'mid' else ()))


def _reverse_whoosh(rng, seed, pitch=0.0, bright=0.5, dur=0.8, width=0.8):
    r = semis(pitch)
    f_hi = min(2600.0 * r * _b(bright), 12000.0)
    a = ins.whoosh(dur, 320.0 * r, f_hi, 'reverse', q=0.9, pan0=-width, pan1=0.0, seed=seed * 7 + 3,
                   lowmix=0.6, fade_out=0.004, air=0.3 * bright)
    b = ins.whoosh(dur, 330.0 * r, f_hi * 1.04, 'reverse', q=0.9, pan0=width, pan1=0.0, seed=seed * 7 + 5,
                   lowmix=0.6, fade_out=0.004, air=0.3 * bright)
    return 0.5 * (a + b)


register(SfxSpec(
    id='reverse_whoosh', fn=_reverse_whoosh, purpose='吸入式蓄力：落版、重击、标题出现之前的“吸气”',
    sync='末端对齐落点：用 align=end 让结尾正好落在 impact / 标题落定那一帧', anchor='end', ref=('mmax', -23.0),
    params={'pitch': P_PITCH, 'bright': P_BRIGHT, 'dur': (0.8, 0.25, 3.0, 'seconds'),
            'width': (0.8, 0.0, 1.0, 'start width (converges to centre)')},
    notes='两路不同种子的反向形状噪声从两侧向中间汇聚，指数上升后 4 ms 收尾。'))


def _tick(rng, seed, pitch=0.0, bright=0.5, dur=0.022):
    return ins.wood_tick(2100.0 * semis(pitch), 1.5, 0.8 + 2.0 * bright, dur, 1.0)


register(SfxSpec(
    id='tick', fn=_tick, purpose='数字滚动、计数、进度点、时钟、逐项出现的小点',
    sync='与数字跳变 / 元素出现同帧；连击时间隔 ≥ 2 帧，末尾一下接 tock 表示锁定', anchor='start', ref=('tp', -18.0),
    params={'pitch': P_PITCH, 'bright': P_BRIGHT, 'dur': (0.022, 0.010, 0.060, 'decay length (s)')},
    notes='2.1 kHz 木质 FM（比率 1.5，指数 10 ms 内归零）。'))


def _tock(rng, seed, pitch=0.0, bright=0.5, dur=0.07):
    return ins.tock(640.0 * semis(pitch), 1.0, index=1.4 + 2.0 * bright, decay=dur / 5.0)


register(SfxSpec(
    id='tock', fn=_tock, purpose='锁定、定格、数值确定、列表行落位',
    sync='与“停住”的那一帧同帧（数字滚动结束、卡片停稳）', anchor='start', ref=('tp', -15.0),
    params={'pitch': P_PITCH, 'bright': P_BRIGHT, 'dur': (0.07, 0.04, 0.20, 'length (s)')},
    notes='640 Hz 木块 FM + 半频正弦鼓体。'))


def _ui_click(rng, seed, pitch=0.0, bright=0.5, dur=0.03):
    r = semis(pitch)
    n = smp(dur + 0.012)
    t = np.arange(n) / SR
    hi = min((3500.0 + 7000.0 * bright) * r, 20000.0)
    nz = bpf(noise(n, seed * 13 + 1), 1500.0 * r, hi) * _att(t, 0.0002) * np.exp(-t / 0.0012)
    tone = np.sin(TWOPI * 3400.0 * r * t) * _att(t, 0.0003) * np.exp(-t / max(0.001, dur * 0.1))
    body = np.sin(TWOPI * 220.0 * r * t) * _att(t, 0.0008) * np.exp(-t / max(0.002, dur * 0.2))
    return 0.8 * nz + (0.2 + 0.3 * bright) * tone + 0.3 * body


register(SfxSpec(
    id='ui_click', fn=_ui_click, purpose='按钮点击、鼠标点选、开关、光标确认',
    sync='与按钮按下（缩放最小 / 颜色变化）同帧', anchor='start', ref=('tp', -16.0),
    params={'pitch': P_PITCH, 'bright': P_BRIGHT, 'dur': (0.03, 0.012, 0.08, 'length (s)')},
    notes='1.5–10 kHz 噪声瞬态 + 3.4 kHz 短音 + 220 Hz 微鼓体。'))


def _typing_key(rng, seed, pitch=0.0, bright=0.5, heavy=0):
    return ins.key_click(rng, heavy=bool(heavy), vel=1.0, pitch=semis(pitch), bright=bright)


register(SfxSpec(
    id='typing_key', fn=_typing_key, purpose='打字、逐字出现的字幕、命令输入；heavy=1 为空格/回车/上屏',
    sync='每个字出现的同一帧放一个（每帧最多一个）；词尾或回车用 heavy=1', anchor='start', ref=('tp', -18.0),
    params={'pitch': P_PITCH, 'bright': P_BRIGHT, 'heavy': (0, 0, 1, '0 letter key, 1 commit/space key')},
    humanize_db=1.2,
    notes='2–4 kHz 带通噪声 3–8 ms + 1.5 kHz 微音高；种子决定 ±5% 音高和 ±1.2 dB 电平，连打不机械。'))


def _pop_soft(rng, seed, pitch=0.0, bright=0.5, dur=0.12):
    r = semis(pitch)
    n = smp(dur + 0.02)
    t = np.arange(n) / SR
    f = 420.0 * r * (1.0 + 1.1 * (1.0 - np.exp(-t / 0.010)))
    ph = TWOPI * np.cumsum(f) / SR
    env = _att(t, 0.0015) * np.exp(-t / (dur * 0.3))
    y = np.sin(ph) * env + 0.15 * bright * np.sin(2 * ph) * env
    click = bpf(noise(n, seed * 17 + 2), 2000.0 * r, min(6500.0 * r, 20000.0)) * _att(t, 0.0002) * np.exp(-t / 0.0015)
    return y + 0.25 * bright * click


register(SfxSpec(
    id='pop_soft', fn=_pop_soft, purpose='图标 / 标签 / 气泡弹出，列表项出现，轻提示',
    sync='与元素缩放到最大（回弹顶点）同帧；多个元素依次出现时间隔 3–5 帧并逐个 pitch +2', anchor='start',
    ref=('tp', -14.0),
    params={'pitch': P_PITCH, 'bright': P_BRIGHT, 'dur': (0.12, 0.06, 0.30, 'length (s)')},
    notes='420→880 Hz 快速上滑正弦（气泡感）+ 少量二次谐波 + 2 ms 噪声点击。'))


def _pluck(rng, seed, pitch=0.0, bright=0.5, dur=1.6, note='A5', space=0.25):
    m = _note({'note': note, 'pitch': pitch}, 'A5')
    y = ins.crystal_pluck(m, 1.0, dur=dur, ratio=2.0, bright=0.6 + 0.8 * bright, seed=seed, decay=dur * 0.25)
    return _space(y, space, 'plate', tail=min(1.2, dur))


register(SfxSpec(
    id='pluck', fn=_pluck, purpose='关键词高亮、要点出现、音乐化的提示（可按音符排成旋律）',
    sync='与高亮出现同帧；多个要点依次出现时用和弦音（note=D5/F#5/A5）', anchor='start', ref=('tp', -14.0),
    params={'pitch': P_PITCH, 'bright': P_BRIGHT, 'dur': (1.6, 0.6, 3.0, 'ring length (s)'),
            'note': ('A5', None, None, 'note name or MIDI number'), 'space': (0.25, 0.0, 1.0, 'plate reverb amount')},
    notes='“在我开口之前”的 crystal pluck：FM 1:2，指数 4→0（约 80 ms），附 4 ms 噪声瞬态，可加合成板式混响。'))


def _bell(rng, seed, pitch=0.0, bright=0.5, dur=3.5, note='A5', space=0.3):
    m = _note({'note': note, 'pitch': pitch}, 'A5')
    y = ins.bell(m, 1.0, dur=dur, index=1.5 + 3.0 * bright, decay=dur * 0.2)
    return _space(y, space, 'hall', tail=1.2)


register(SfxSpec(
    id='bell', fn=_bell, purpose='章节开始、结论出现、“叮”一下的高光时刻、片尾',
    sync='与标题 / 结论落定同帧；前面可接 reverse_whoosh（align=end 对同一帧）', anchor='start', ref=('tp', -14.0),
    params={'pitch': P_PITCH, 'bright': P_BRIGHT, 'dur': (3.5, 1.5, 6.0, 'ring length (s)'),
            'note': ('A5', None, None, 'note name or MIDI number'), 'space': (0.3, 0.0, 1.0, 'hall reverb amount')},
    notes='FM 1:3.5 非谐波钟 + 基频拍频暖层 + 半频 hum，带合成大厅混响。'))


def _impact_soft(rng, seed, pitch=0.0, bright=0.5, dur=0.6):
    r = semis(pitch)
    n = smp(dur)
    t = np.arange(n) / SR
    body = np.sin(TWOPI * np.cumsum(110.0 * r * (1 + 0.5 * np.exp(-t / 0.012))) / SR) * _att(t, 0.001) * np.exp(-t / 0.12)
    thud = ins.boom(70.0 * r, 48.0 * r, dur, 1.0, glide_tau=0.12, decay=dur * 0.3, sat=1.1)
    out = np.zeros((2, n))
    for ch in range(2):
        nz = lp(noise(n, seed * 19 + ch), 900.0 + 2500.0 * bright, 2) * _att(t, 0.0008) * np.exp(-t / 0.035)
        out[ch] = 0.6 * thud + 0.5 * body + 0.35 * nz
    return out


register(SfxSpec(
    id='impact_soft', fn=_impact_soft, purpose='元素落定、卡片放下、轻量强调、文字砸到位',
    sync='与落定（位移结束、回弹前）同帧', anchor='start', ref=('tp', -12.0),
    params={'pitch': P_PITCH, 'bright': P_BRIGHT, 'dur': (0.6, 0.3, 1.5, 'length (s)')},
    notes='70→48 Hz 短 boom + 110 Hz 鼓体下滑 + 低通噪声（亮度控制截止）。'))


def _impact_big(rng, seed, pitch=0.0, bright=0.5, dur=1.8, tail=0.5):
    r = semis(pitch)
    n = smp(dur)
    t = np.arange(n) / SR
    b = ins.boom(50.0 * r, 35.0 * r, dur, 1.0)
    body = np.sin(TWOPI * np.cumsum(95.0 * r * (1 + 0.6 * np.exp(-t / 0.015))) / SR) * _att(t, 0.001) * np.exp(-t / 0.16)
    out = np.zeros((2, n))
    for ch in range(2):
        nz = lp(noise(n, seed * 23 + ch), 1400.0 + 2000.0 * bright, 2) * _att(t, 0.0008) * np.exp(-t / 0.18)
        crash = lp(hp(noise(n, seed * 23 + 7 + ch), 3500.0, 2), 7000.0 + 4000.0 * bright, 2)
        crash *= _att(t, 0.0005) * np.exp(-t / (0.2 + 0.4 * tail)) * (0.03 + 0.07 * tail * (0.5 + bright))
        out[ch] = 0.9 * b + 0.55 * body + 0.32 * nz + crash
    out[:, :24] *= rc_ramp(24)
    return _space(out, 0.35 * tail, 'room', tail=0.6)


register(SfxSpec(
    id='impact_big', fn=_impact_big, purpose='大标题落版、段落高潮、反转、drop 点',
    sync='与画面重击同帧；前面接 riser 或 reverse_whoosh（align=end 同一帧）', anchor='start', ref=('tp', -8.0),
    params={'pitch': P_PITCH, 'bright': P_BRIGHT, 'dur': (1.8, 0.8, 3.0, 'length (s)'),
            'tail': (0.5, 0.0, 1.0, 'crash / room tail amount')},
    notes='50→35 Hz boom + 95 Hz 鼓体 + 低通噪声 + 高通噪声 crash 尾 + 合成房间混响。'))


def _riser(rng, seed, pitch=0.0, bright=0.5, dur=2.5, octaves=1.0):
    return ins.riser(dur, 110.0 * semis(pitch), seed=seed * 29 + 1, vel=1.0, octaves=octaves,
                     fc_end=3000.0 + 9000.0 * bright)


register(SfxSpec(
    id='riser', fn=_riser, purpose='蓄力、悬念、倒计时、进入高潮前',
    sync='用 align=end：结尾对准 drop / impact 那一帧（结尾 20 ms 收口，接重击不会双响）', anchor='end',
    ref=('mmax', -21.0),
    params={'pitch': P_PITCH, 'bright': P_BRIGHT, 'dur': (2.5, 0.8, 8.0, 'seconds'),
            'octaves': (1.0, 0.25, 2.0, 'pitch rise')},
    notes='带限锯齿上升 + 打开的低通滤波 + 噪声，指数渐强。'))


def _sub_drop(rng, seed, pitch=0.0, bright=0.5, dur=1.4):
    r = semis(pitch)
    n = smp(dur)
    t = np.arange(n) / SR
    f = 32.0 * r + (88.0 * r - 32.0 * r) * np.exp(-t / (0.28 * dur))
    y = np.sin(TWOPI * np.cumsum(f) / SR) * _att(t, 0.004) * np.exp(-t / (0.45 * dur))
    sat = 1.0 + 2.0 * bright
    return np.tanh(sat * y) / np.tanh(sat)


register(SfxSpec(
    id='sub_drop', fn=_sub_drop, purpose='低频下沉：重击的低频层、情绪下坠、黑场',
    sync='与 impact 同帧叠用；单用时与画面下沉 / 黑场同帧。手机外放主要靠 bright 带出的谐波', anchor='start',
    ref=('tp', -14.0),
    params={'pitch': P_PITCH, 'bright': P_BRIGHT, 'dur': (1.4, 0.5, 3.0, 'seconds')},
    notes='88→32 Hz 指数下滑正弦，tanh 饱和（bright 越大谐波越多，手机外放越听得见）。'))


def _glitch(rng, seed, pitch=0.0, bright=0.5, dur=0.3, density=0.5):
    r = semis(pitch)
    n = smp(dur)
    os_ = 4
    out = np.zeros((2, n))
    t = 0.0
    k = 0
    while t < dur - 0.006:
        seg = float(rng.uniform(0.008, 0.045) * (1.3 - 0.8 * density))
        seg = min(seg, dur - t)
        m = smp(seg)
        if m < 64:
            break
        kind = rng.choice(['buzz', 'noise', 'fm', 'sh', 'gap'], p=[0.26, 0.2, 0.2, 0.22, 0.12])
        tt = np.arange(m) / SR
        if kind == 'buzz':          # band-limited square at a random pitch
            f = float(rng.uniform(180, 900)) * r
            y = np.zeros(m)
            for h in range(1, 60, 2):
                if f * h > 11000 * (0.6 + 0.8 * bright):
                    break
                y += np.sin(TWOPI * f * h * tt) / h
            y *= 0.8
        elif kind == 'noise':
            y = bpf(noise(m, seed * 31 + k), 800.0 * r, min(3000.0 + 9000.0 * bright, 20000.0), 2)
        elif kind == 'fm':
            f = float(rng.uniform(300, 2400)) * r
            y = np.sin(TWOPI * f * tt + 3.0 * np.sin(TWOPI * f * 1.41 * tt))
        elif kind == 'sh':          # sample-and-hold ("bit-crushed") noise, rendered 4x then decimated
            hold = int(rng.integers(6, 40)) * os_
            src = noise(m * os_ // hold + 2, seed * 31 + 100 + k)
            y = decimate(np.repeat(src, hold)[: m * os_], os_)[:m] * 0.7
        else:
            y = np.zeros(m)
        rr = min(m // 2, smp(0.0006))
        y[:rr] *= rc_ramp(rr)
        y[m - rr:] *= rc_ramp(rr)[::-1]
        p = float(rng.uniform(-0.7, 0.7))
        s0 = smp(t)
        e = min(n, s0 + m)
        out[:, s0:e] += stereo(y[: e - s0], p)
        t += seg
        k += 1
    return out


register(SfxSpec(
    id='glitch', fn=_glitch, purpose='数字故障、信息错误、画面抖动 / 撕裂、AI 出错的梗',
    sync='覆盖画面故障帧的起止（dur 设成故障持续时长）；与第一帧抖动同帧开始', anchor='start', ref=('tp', -14.0),
    params={'pitch': P_PITCH, 'bright': P_BRIGHT, 'dur': (0.3, 0.08, 1.5, 'seconds'),
            'density': (0.5, 0.0, 1.0, 'fragment rate')},
    notes='8–45 ms 碎片随机拼接：带限方波、带通噪声、FM、4× 过采样的采样保持噪声、静音，每片随机声像。'))


def _stamp(rng, seed, pitch=0.0, bright=0.5):
    r = semis(pitch)
    y = ins.stamp(1.0, seed=seed * 37 + 1, f=70.0 * r, paper=0.2 + 0.4 * bright)
    t = np.arange(len(y)) / SR
    y += 0.3 * np.sin(TWOPI * 165.0 * r * t) * _att(t, 0.001) * np.exp(-t / 0.018)
    return y


register(SfxSpec(
    id='stamp', fn=_stamp, purpose='盖章、打勾确认、“已完成”、印记落下',
    sync='与印章接触纸面（缩放到最小）同帧', anchor='start', ref=('tp', -10.0),
    params={'pitch': P_PITCH, 'bright': P_BRIGHT},
    notes='70 Hz / 80 ms 闷击 + 165 Hz 中低频层（手机可闻）+ 30 ms 纸面噪声。'))


_PENTA = [0, 2, 4, 7, 9]


def _shimmer(rng, seed, pitch=0.0, bright=0.5, dur=1.2, density=0.5, root='D'):
    r = midi(root + '6') + pitch
    notes = [r + o + 12 * k for k in (0, 1) for o in _PENTA]
    n = smp(dur)
    out = np.zeros((2, n + smp(0.25)))
    t = 0.0
    while True:
        rate = (10.0 + 30.0 * density) * np.exp(-t / (0.5 * dur)) + 3.0
        t += float(rng.exponential(1.0 / rate))
        if t >= dur - 0.05:
            break
        m = notes[int(rng.integers(len(notes)))]
        g = ins.grain(hz(m) * (1 + rng.uniform(-0.0015, 0.0015)), float(rng.uniform(0.05, 0.16)),
                      float(rng.uniform(0.55, 1.0)) * np.exp(-t / (0.7 * dur)), 1.0, 0.0, 0.1)
        s0 = smp(t)
        seg = stereo(g, float(rng.uniform(-0.85, 0.85)))
        out[:, s0:s0 + seg.shape[1]] += seg[:, : out.shape[1] - s0]
    air = hp(noise(n, seed * 41 + 3), 6000, 2)
    air = lp(air, 11000, 2) * np.sin(np.pi * np.linspace(0, 1, n)) ** 2 * (0.02 + 0.06 * bright)
    out[:, :n] += np.vstack([air, np.roll(air, 480)])
    return _space(out, 0.4, 'hall', tail=0.8)


register(SfxSpec(
    id='shimmer', fn=_shimmer, purpose='闪光、魔法感、AI 生成完成、画面变亮、星点',
    sync='与闪光 / 高亮开始同帧；dur 与闪光持续时间一致', anchor='start', ref=('mmax', -26.0),
    params={'pitch': P_PITCH, 'bright': P_BRIGHT, 'dur': (1.2, 0.4, 4.0, 'seconds'),
            'density': (0.5, 0.0, 1.0, 'grain rate'), 'root': ('D', None, None, 'pentatonic root (C..B, # b ok)')},
    notes='高音区五声音阶正弦颗粒云（密度随时间衰减）+ 6–11 kHz 空气噪声 + 合成大厅混响。'))


def _blip(rng, seed, pitch=0.0, bright=0.5, dur=0.2):
    return ins.blip(hz('D6') * semis(pitch), 1.0, index=0.6 + 1.6 * bright, decay=dur * 0.3)


register(SfxSpec(
    id='blip', fn=_blip, purpose='启动、界面出现、通知小点、数据点亮起',
    sync='与元素出现第一帧同帧', anchor='start', ref=('tp', -16.0),
    params={'pitch': P_PITCH, 'bright': P_BRIGHT, 'dur': (0.2, 0.1, 0.5, 'length (s)')},
    notes='FM 1:2 近正弦 D6 + 微小上滑（-40 cents→0）。'))


def _laser_zip(rng, seed, pitch=0.0, bright=0.5, dur=0.05):
    r = semis(pitch)
    return ins.laser_zip(1.0, f0=min(5000.0 * r * _b(bright, 0.8), 16000.0), f1=1800.0 * r, dur=dur, seed=seed * 43 + 1)


register(SfxSpec(
    id='laser_zip', fn=_laser_zip, purpose='切分、扫描线、划线、裁切、快速下划线',
    sync='与切线 / 扫描开始同帧；dur 等于划过所需时间', anchor='start', ref=('tp', -16.0),
    params={'pitch': P_PITCH, 'bright': P_BRIGHT, 'dur': (0.05, 0.03, 0.25, 'sweep time (s)')},
    notes='5000→1800 Hz 正弦下扫 + 跟随带通噪声。'))


def _clack(rng, seed, pitch=0.0, bright=0.5, zap=0.0):
    r = semis(pitch)
    y = ins.clack(1.0, seed=seed * 47 + 1, f=900.0 * r)
    if bright != 0.5:
        y = y + (bright - 0.5) * 0.6 * hp(y, 3000, 2)
    if zap > 0:
        z = ins.zap(1.0, 1600.0 * r, 150.0 * r)
        m = max(len(y), len(z))
        y = np.pad(y, (0, m - len(y))) + 0.55 * zap * np.pad(z, (0, m - len(z)))
    return y


register(SfxSpec(
    id='clack', fn=_clack, purpose='锁定、卡扣、选中框锁住、最终确认（zap>0 带电子尾巴）',
    sync='与锁定帧同帧', anchor='start', ref=('tp', -14.0),
    params={'pitch': P_PITCH, 'bright': P_BRIGHT, 'zap': (0.0, 0.0, 1.0, 'electric zap layer')},
    notes='塑料 / 木质 clack（噪声 + FM 2.3 + 160 Hz 体）+ 可选下行 FM zap。'))


def catalog_rows(family=None):
    rows = []
    for sid in list_sfx(family):
        s = REGISTRY[sid]
        y = render_sfx(sid, seed=0)
        rows.append(dict(id=sid, family=s.family, purpose=s.purpose, sync=s.sync, anchor=s.anchor,
                         ref='%s %.1f %s' % ('TP' if s.ref[0] == 'tp' else 'M-max', s.ref[1],
                                             'dBTP' if s.ref[0] == 'tp' else 'LUFS'),
                         default_len=y.shape[1] / SR, params=s.params, notes=s.notes, aliases=s.aliases))
    return rows
